### ISSUE TITLE
Checking grammar definition with the BNF Converter

### ISSUE THREAD

**Issue by walter-weinmann** [opencypher/openCypher#240] opened 2017-06-22 13:52 UTC
I have checked the current status of the grammar definition (EBNF version as of June 21, 2017) with the [BNF Converter](https://github.com/bnfc/bnfc). The following issues were discovered:

Unused rules:
---
1. one of (hence also reduce / reduce conflict):
```
PatternElement = (NodePattern, { [SP], PatternElementChain })
               | ...

RelationshipsPattern = NodePattern, { [SP], PatternElementChain }- ;
```
2. one of (hence also reduce / reduce conflict):
```
ReservedWord = (A,L,L)
               | ...

SymbolicName = ...
             | (A,L,L)
             | ...
```
Reduce / reduce conflicts:
---
1. MapLiteral :
```
Properties = MapLiteral
           | ...

Literal = ...
        | MapLiteral
        | ...
```
2. Parameter :
```
Properties = ...
           | Parameter
           ;

Atom = ..
     | Parameter
     | ...
```

Is there any chance of solving these issues in the grammar definition ?

**Comment by Mats-SX** [comment] 2017-06-27 11:34
@walter-weinmann Thanks for reporting this. So the problem is that these rules occur with the same definitions in multiple places? Do you think that simply refactoring them to their own rules and referencing that rule in the current places would be enough?

**Comment by walter-weinmann** [comment] 2017-06-27 12:09
@Mats-SX  My problem is that I'm using a LALR parser, namely yecc, which is the Erlang foe to yacc. LALR parsers are however bottom up parsers with only limited lookahead.

**Comment by Mats-SX** [comment] 2017-07-06 09:49
@walter-weinmann I don't think I understand exactly what the problem is, so I don't know how to solve it. Your first headline reads 'unused rules', but I don't understand in what sense they are unused? It's certainly possible to write a query which will use any or both of these rules.

Do you have a particular query that is impossible to parse?

For `ALL`, I think that's a bug and should be removed. `ALL` is reserved, and not allowed as a symbolic name (pushed a fix).

**Closed** 2017-11-18 09:12 UTC
Labels: bug, grammar
